# Generated by Django 2.1 on 2018-08-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='priority',
            field=models.IntegerField(default=100, help_text='Table with higher priority are preferred when creating new turns.'),
        ),
    ]
