# Generated by Django 2.1 on 2018-08-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='bye_score',
            field=models.DecimalField(decimal_places=1, default=3, help_text='Score to assign for a bye.', max_digits=4),
        ),
    ]
