# Generated by Django 2.1.9 on 2019-06-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournament_max_players_per_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='max_players_per_team',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Maximum number of allowed players per team during registration. If no value is given, the number is unlimited. If 0 is given, player registration is disabled.', null=True),
        ),
    ]
