# Generated by Django 2.1 on 2018-08-09 21:11

from django.db import migrations, models
import django.db.models.deletion
import tournament.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_table_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=tournament.models.Turn.number_default)),
            ],
            options={
                'get_latest_by': 'number',
            },
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Team'),
        ),
        migrations.AlterField(
            model_name='table',
            name='priority',
            field=models.IntegerField(default=100, help_text='Tables with higher priority are preferred when creating a new turn.'),
        ),
    ]
