# Generated by Django 2.1 on 2018-08-10 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20180810_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='table',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Table'),
        ),
    ]
