# Generated by Django 2.2.2 on 2019-07-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20190622_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='short_name',
            field=models.CharField(blank=True, default=None, help_text='Name to show on mobile devices.', max_length=255, null=True),
        ),
    ]
