# Generated by Django 2.1 on 2018-08-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20180809_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turn',
            options={'get_latest_by': 'number', 'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='turn',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
