# Generated by Django 2.2.3 on 2019-07-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_tournament_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True, default=None, help_text='This appears at the beginning of the public page. You can use HTML tags.', null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_players_per_team',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Maximum number of allowed players per team during registration. If no value is given, the number is unlimited (probably unsupported!). If 0 is given, player registration is disabled.', null=True),
        ),
    ]
