# Generated by Django 2.1.7 on 2019-03-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20180820_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='shown_players',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='Number of players shown in the scoreboard. If no value is given, all players are shown.', null=True),
        ),
    ]
