# Generated by Django 2.1.7 on 2019-03-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_tournament_shown_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='shown_players',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='Number of players to show in the scoreboard. If no value is given, all players are shown.', null=True),
        ),
    ]
