# Generated by Django 2.1.7 on 2019-03-07 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_auto_20190301_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
