# Generated by Django 2.2.3 on 2019-08-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_auto_20190801_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='phantom_score',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, help_text='Used to break ties in the player scoreboard (e.g. if a tiebreaker is played after the regular tournament). It does not affect the shown score.', max_digits=4, null=True),
        ),
    ]
