# Generated by Django 2.1.7 on 2019-03-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_auto_20190307_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='visibility',
            field=models.CharField(choices=[('H', 'Hide'), ('R', 'Hide results'), ('S', 'Show')], default='S', max_length=2),
        ),
        migrations.AddField(
            model_name='tournament',
            name='default_round_visibility',
            field=models.CharField(choices=[('H', 'Hide'), ('R', 'Hide results'), ('S', 'Show')], default='S', help_text='Default visibility of generated rounds.', max_length=2),
        ),
    ]
