# Generated by Django 2.1.9 on 2019-06-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_auto_20190307_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_registration_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_teams',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Maximum number of allowed teams during registration. If no value is given, the number is unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='default_round_visibility',
            field=models.CharField(choices=[('H', 'Hide'), ('R', 'Hide results'), ('S', 'Show')], default='S', help_text='Default visibility of newly generated rounds.', max_length=2),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='shown_players',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of players to show in the scoreboard. If no value is given, all players are shown. If 0, the player scoreboard is not shown.', null=True),
        ),
    ]
