# Generated by Django 2.1.9 on 2019-06-20 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_auto_20190617_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='table',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.Table'),
        ),
    ]
