# Generated by Django 2.1.9 on 2019-06-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_auto_20190620_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('team', 'name')},
        ),
    ]
