# Generated by Django 2.1.9 on 2019-06-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_auto_20190620_2116'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set(),
        ),
    ]
